"""empty message

Revision ID: 28d2f96b7e43
Revises: 91991a3c055c
Create Date: 2018-06-28 21:40:33.366264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d2f96b7e43'
down_revision = '91991a3c055c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('content', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'content')
    # ### end Alembic commands ###
