"""empty message

Revision ID: 91991a3c055c
Revises: 
Create Date: 2018-06-28 21:36:54.049817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91991a3c055c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###
